# --------------------------------------------- #
# Note: this file originates in template-docker #
# --------------------------------------------- #

name: push

on:
  - push
  - workflow_dispatch

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}

jobs:
  metadata:
    uses: ahmadnassri/actions/.github/workflows/push-docker.yml@master
